#we can use docker-compose-dev, and just addon/replace the differences we need.
services:
  api-node:
    command:
      - "npm"
      - "run"
      - "test"
    ports:
      - "3000:3000"
      - "9229:9229"
  api-golang:
    working_dir: /go/web/docker/example-web-application/api-golang
    command:
      - "go"
      - "test"
      - "-v"
      - "./..."
    ports:
      - "8080:8080"
      - "4000:4000"
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - SYS_PTRACE