// @generated by protoc-proto-es v2.2.3 with parameter "target=ts"
// @generated from file response.proto (package message, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message as Message$1 } from "@bufbuild/protobuf";

/**
 * Describes the file response.proto.
 */
export const file_response: GenFile = /*@__PURE__*/
  fileDesc("Cg5yZXNwb25zZS5wcm90bxIHbWVzc2FnZSInCgdNZXNzYWdlEg8KB21lc3NhZ2UYASABKAkSCwoDbnVtGAIgASgFQgRaAi4vYgZwcm90bzM");

/**
 * @generated from message message.Message
 */
export type Message = Message$1<"message.Message"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;

  /**
   * @generated from field: int32 num = 2;
   */
  num: number;
};

/**
 * Describes the message message.Message.
 * Use `create(MessageSchema)` to create a new message.
 */
export const MessageSchema: GenMessage<Message> = /*@__PURE__*/
  messageDesc(file_response, 0);

